### PR TITLE
Added package.json for NPM support

### LINKED ISSUE #17: Publish on NPM
It'd be nice if this repo was published on NPM so that the schema could easily be required within a project.

### PR DESCRIPTION
**Pull request by RangerMauve**
Closes #17 

This is all the changes needed to support NPM. After another collaborator OKs this I'll publish it to NPM. If anyone has an NPM account, I'll add you as a collaborator for the package if you give me your username.

Also added a bit of text to the README.

### CODE REVIEW

**Comment by abargnesi** [comment]
This looks good, thanks. You can add my [profile (abargnesi)](https://www.npmjs.com/~abargnesi) on npm.

**Comment by RangerMauve** [comment]
Published, and added you. https://www.npmjs.com/package/json-graph-specification

:fireworks:

**Comment by RangerMauve** [comment]
I'll probably get started on the validator library tomorrow. In the meantime I'm working on the [graphlib integration](https://github.com/jsongraph/graphlib-json-graph)

**Comment by abargnesi** [comment]
Nice work! :tada:

**Pull request merged**
